name: Create Repositories

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to the configuration file'
        required: true

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  CONFIG_PATH: ${{ github.event.inputs.config_path }}

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Install jq 1.6
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
          chmod +x jq
          sudo mv jq /usr/bin/jq

      - name: Create Repositories
        run: |
          ORG_NAME="AngelNav"
          
          # Sign in to GitHub CLI with access token
          gh auth login --with-token <<<"$PAT_TOKEN"
          
          # Debug print
          echo "CONFIG_PATH: $CONFIG_PATH"
          
          # Parse JSON and create repositories
          jq -r '.repos[] | "\(.repo_name),\(.template_name)"' "$CONFIG_PATH" |
          while IFS=, read -r repo_name template; do
            repo_name=$(echo "$repo_name" | tr -d '[:space:]')  # Eliminar espacios en blanco
            template=$(echo "$template" | tr -d '[:space:]')  # Eliminar espacios en blanco
      
            echo "Processing repo: $repo_name - Template: $template"
            # Create a new repository from the template
            gh repo create "$ORG_NAME/$repo_name" --private --template "$ORG_NAME/$template"
          done
