name: Create Repositories

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to the configuration file'
        required: true

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  CONFIG_PATH: ${{ github.event.inputs.config_path }}

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Install jq 1.6
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O jq
          chmod +x jq
          sudo mv jq /usr/bin/jq

      - name: Create Repositories
        run: |
          ORG_NAME="AngelNav"

          # Sign in to GitHub CLI with access token
          gh auth login --with-token <<<"$PAT_TOKEN"
          
          # Parse JSON and create repositories
          for repo in $(echo "$CONFIG_CONTENT" | jq -c '.repos[]'); do
              echo "Processing repo: $repo"
              REPO_NAME=$(echo $repo | jq -r '.repo_name')
              TEMPLATE_REPO=$(echo $repo | jq -r '.template_name')
        
              # Debug prints
              echo "REPO_NAME: $REPO_NAME"
              echo "TEMPLATE_REPO: $TEMPLATE_REPO"
        
              # Create a new repository from the template
              gh repo create "${ORG_NAME}/${REPO_NAME}" --private --template "${ORG_NAME}/${TEMPLATE_REPO}"
          done

