name: Create Repositories

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to the configuration file'
        required: true

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  CONFIG_PATH: ${{ github.event.inputs.config_path }}

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create Repositories
        run: |
          ORG_NAME="MGMResorts"

          # Sign in to GitHub CLI with access token
          gh auth login --with-token <<<"$PAT_TOKEN"
          
          # Parse JSON and create repositories
          for repo in $(echo "$CONFIG_PATH" | jq -c '.repos[]'); do
              REPO_NAME=$(echo $repo | jq -r '.repo_name')
              TEMPLATE_REPO=$(echo $repo | jq -r '.template_name')

              # Create a new repository from the template
              gh repo create "${ORG_NAME}/${REPO_NAME}" --private --template "${ORG_NAME}/${TEMPLATE_REPO}"
          done

