name: Create Repositories

on:
  workflow_dispatch:
    inputs:
      config_path:
        description: 'Path to the configuration file'
        required: true

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  create-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Load Configuration
        id: load-config
        run: echo "::set-output name=config::$(cat ${{ github.event.inputs.config_path }})"

      - name: Create Repositories
        run: |
          CONFIG_PATH="${{ github.event.inputs.config_path }}"
          ORG_NAME="MGMResorts"
          
          # Parse JSON and create repositories
          for repo in $(jq -c '.repos[]' <<< "${{ steps.load-config.outputs.config }}"); do
            REPO_NAME=$(echo $repo | jq -r '.repo_name')
            TEMPLATE_REPO=$(echo $repo | jq -r '.template_name')

            # Sign in to GitHub CLI with access token
            gh auth login --with-token <<<"$PAT_TOKEN"

            # Create a new repository from the template
            gh repo create "${ORG_NAME}/${REPO_NAME}" --private --template "${ORG_NAME}/${TEMPLATE_REPO}"
          done
